services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AASHRO\GoodFood\EventListener\PackageActivationListener:
    tags:
      - name: event.listener
        identifier: 'package.activation'